#!/usr/bin/env bash
# This script displays username, user id, and home directory from /etc/passwd

# Open /etc/passwd and read it line by line
while IFS=: read -r username password uid gid full_name home shell; do
    echo "$username $uid $home"
done < /etc/passwd
