#!/usr/bin/env bash

#dfhdhfdh
IFS=':'

#gdh
while read -r username password userid groupid fullname homedir shell; do
    # Display the information in the required format
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell."
    echo "USER ID's place is protected by the passcode $password, more info about the user here: $fullname"
    echo "---------------------------------------------"
done < /etc/passwd
