#!/usr/bin/env bash

# Set IFS to colon ':' to split fields
IFS=':'

#afsafa
while read -r username password userid groupid fullname homedir shell; do
    #asfasfa
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell."
    echo "USER ID's place is protected by the passcode $password, more info about the user here: $fullname"
    echo "---------------------------------------------"
done < /etc/passwd
