#!/usr/bin/env bash
#sfsa
while read -r USERNAME PASSWORD USER_ID GROUP_ID GECOS HOME_DIRECTORY COMMAND_SHELL
do
	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMADN_SHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $GECOS"
done < /etc/passwd

