#!/usr/bin/env bash
#safsf
for file in *; do
    # Yalnız görünən fayllar və qovluqlar
    if [ -f "$file" ]; then
        # Faylın adında tire varsa
        if [[ "$file" == *-* ]]; then
            echo "${file#*-}"
        else
            echo "$file"
        fi
    fi
