#!/usr/bin/env bash
# asfasfas
# asfa
#asf

for file in *; do
    # Yalnız faylları nəzərə al
    if [ -f "$file" ]; then
        # Faylın adında tire varsa
        if [[ "$file" == *-* ]]; then
            echo "${file#*-}"
        else
            echo "$file"
        fi
    fi
done
