#!/usr/bin/env bash
# asfasf

PIDFILE="/tmp/myscript.pid"
echo $$ > "$PIDFILE"

sigint_handler() {
    echo "Y U no love me?!"
}

sigterm_handler() {
    echo "I hate the kill command"
    rm -f "$PIDFILE"
    exit 0
}

sigquit_handler() {
    rm -f "$PIDFILE"
    exit 0
}

trap sigint_handler SIGINT
trap sigterm_handler SIGTERM
trap sigquit_handler SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 1
done
