#!/usr/bin/env bash
# asfasf
#!/bin/bash

PIDFILE="/tmp/myscript.pid"

echo $$ > "$PIDFILE"

sigint_handler() {
    echo "Y U no love me?!"
}

sigterm_handler() {
    echo "I hate the kill command"
    rm -f "$PIDFILE"
    exit 0
}

sigquit_handler() {
    rm -f "$PIDFILE"
    exit 0
}

trap sigint_ha_

