#!/usr/bin/env bash
#sdgdgsdg
pid=$(ps aux | grep "To infinity and beyond" | grep -v grep | awk '{print $2}')

#asfasfas
if [ -n "$pid" ]; then
    echo "Stopping the 'To infinity and beyond' process with PID $pid..."
    kill "$pid"  
else
    echo "No 'To infinity and beyond' process found."
fi
