#!/usr/bin/env bash
# asfasf
pid=$(pgrep -f "To infinity and beyond")

# asfas
if [ -n "$pid" ]; then
    echo "Stopping the 'To infinity and beyond' process with PID $pid..."
    kill "$pid"  # asfasf
else
    echo "No 'To infinity and beyond' process found."
fi
