#!/usr/bin/env bash
# asfa

# 7-asfasf
pid=$(pgrep -f "7-highlander")

if [ -n "$pid" ]; then
    echo "7-highlander prosesi tapıldı, PID: $pid"
    kill -SIGSTOP "$pid" && echo "7-highlander prosesi dayandırıldı (SIGSTOP)."
else
    echo "Heç bir '7-highlander' prosesi tapılmadı."
fi
